-- CREATE DATABASE PIZZA_HUT

USE PIZZA_HUT;

-- Retrieve the total number of orders placed.orders

SELECT 
    COUNT(ORDER_ID) AS total_orders
FROM
    ORDERS;


-- Calculate the total revenue generated from pizza sales.

SELECT 
    ROUND(SUM(PIZZAS.PRICE * ORDER_DETAILS.QUANTITY)) AS TOTAL_SALES
FROM
    ORDER_DETAILS
        INNER JOIN
    PIZZAS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID;
    
    
-- Identify the highest-priced pizza.

SELECT 
    PIZZA_TYPES.NAME,
    PIZZA_TYPES.CATEGORY,
    PIZZA_TYPES.INGREDIENTS,
    PIZZAS.PRICE
FROM
    PIZZA_TYPES
        INNER JOIN
    PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
WHERE
    PIZZAS.PRICE = (SELECT 
            MAX(PRICE)
        FROM
            PIZZAS);


-- List the top 5 most ordered pizza types along with their quantities.

SELECT 
    PIZZA_TYPES.NAME, SUM(ORDER_DETAILS.QUANTITY) AS TOTAL_QUANTITY
FROM
    PIZZAS
        JOIN
    PIZZA_TYPES ON PIZZAS.PIZZA_TYPE_ID = PIZZA_TYPES.PIZZA_TYPE_ID
        JOIN
    ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY SUM(ORDER_DETAILS.QUANTITY) DESC
LIMIT 5;


-- find the total quantity of each pizza category ordered.

SELECT 
    PIZZA_TYPES.CATEGORY,
    SUM(ORDER_DETAILS.QUANTITY) AS TOTAL_QUANTITY
FROM
    PIZZA_TYPES
        JOIN
    PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
        JOIN
    ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.CATEGORY
ORDER BY TOTAL_QUANTITY DESC;


-- Determine the distribution of orders by hour of the day.

SELECT 
    HOUR(TIME) AS ORDER_HOUR,
    COUNT(ORDER_ID) AS TOTAL_ORDERS
FROM
    ORDERS
GROUP BY HOUR(TIME)
ORDER BY HOUR(TIME);


-- Group the orders by date and calculate the average number of pizzas ordered per day.

SELECT 
    ROUND(AVG(SUM)) AS AVERAGE
FROM
    (SELECT 
        ORDERS.DATE, SUM(ORDER_DETAILS.QUANTITY) AS SUM
    FROM
        ORDERS
    JOIN ORDER_DETAILS ON ORDERS.ORDER_ID = ORDER_DETAILS.ORDER_ID
    GROUP BY ORDERS.DATE) AS XYZ;


-- Determine the top 3 most ordered pizza types based on revenue.

SELECT 
    PIZZA_TYPES.NAME, SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS TOTAL_REVENUE
FROM
    PIZZA_TYPES
        JOIN
    PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
        JOIN
    ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) DESC
LIMIT 3;


-- Calculate the percentage contribution of each pizza type to total revenue.

SELECT 
    PIZZA_TYPES.NAME,
    SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) / (SELECT 
            SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE)
        FROM
            PIZZA_TYPES
                JOIN
            PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
                JOIN
            ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID) * 100 AS PERCENTAGE
FROM
    PIZZA_TYPES
        JOIN
    PIZZAS ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
        JOIN
    ORDER_DETAILS ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
GROUP BY PIZZA_TYPES.NAME
ORDER BY SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) DESC;


-- Analyze the cumulative revenue generated over time.

SELECT 
    DATE,
    REVENUE,
    ROUND(SUM(REVENUE) OVER (
        ORDER BY DATE
    ),2) AS CUMULATIVE_REVENUE
FROM
(
    SELECT 
        ORDERS.DATE,
        SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
    FROM ORDER_DETAILS
    JOIN PIZZAS
        ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
    JOIN ORDERS
        ON ORDER_DETAILS.ORDER_ID = ORDERS.ORDER_ID
    GROUP BY 
        ORDERS.DATE
) AS SALES;


-- Determine the top 3 most ordered pizza types based on revenue for each pizza category.

SELECT 
    CATEGORY,
    NAME,
    REVENUE,
    RANKING
FROM
(
    SELECT 
        CATEGORY,
        NAME,
        REVENUE,
        RANK() OVER (
            PARTITION BY CATEGORY 
            ORDER BY REVENUE DESC
        ) AS RANKING
    FROM
    (
        SELECT 
            PIZZA_TYPES.CATEGORY,
            PIZZA_TYPES.NAME,
            SUM(ORDER_DETAILS.QUANTITY * PIZZAS.PRICE) AS REVENUE
        FROM ORDER_DETAILS
        JOIN PIZZAS
            ON ORDER_DETAILS.PIZZA_ID = PIZZAS.PIZZA_ID
        JOIN PIZZA_TYPES
            ON PIZZA_TYPES.PIZZA_TYPE_ID = PIZZAS.PIZZA_TYPE_ID
        GROUP BY 
            PIZZA_TYPES.CATEGORY,
            PIZZA_TYPES.NAME
    ) AS A
) AS B
WHERE RANKING <= 3;


